# -------- Stage 1: Build --------
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN go build -o server cmd/server/main.go

# -------- Stage 2: Runtime --------
FROM alpine:3.22

WORKDIR /app

# ✅ Install CA certificates
RUN apk --no-cache add ca-certificates

COPY --from=builder /app/server .

EXPOSE 5000

CMD ["./server"]
